name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # once a day
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: mlhv

      - name: Commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f profile-3d-contrib/
          git commit -m "Update 3D contribution graph" || exit 0
          git push